### ISSUE TITLE
Mutagens

### ISSUE THREAD

**Issue by analysisparalysis23** [Truinto/SpellPouch#14]
Does anyone have a list for all the Mutagen guids so I can put them into a group as well? Thanks.

**Comment by Truinto** [comment]
Toybox has an option to show ability guids under the display name.
But really, you can just press shift and drag&drop the abilities into a new group. The readme on this page has a detailed description.

**Comment by analysisparalysis23** [comment]
Yeah, I just recalled earlier today and have been playing around with it for a bit.

I noticed that older abilities get displaced by the newer ones, Greater Mutagen by Grand Cognatogen but this doesn't seem to work entirely for Cognatogens. With the code I entered below into DefGroups, two of the Greater Cognatogens remained while the other 4 were removed upon getting Grand Cognatogens which struck me as odd.


  {
    "Title": "Alchemist Mutagens",
    "Description": "",
    "Guids": [
      "859629f49f06cd04492b1ba455a9b31b",      
      "b11d314d60f7a38498d1ed6933fe1638",
      "7af42862f58edcc4cb825862ff2a0d10",
	  
      "c1e46599fcade78418ef1ada71c1f487",	  
      "c942e12092a433440bbc73965b842c8a",
      "73b97114bf2f9914bba305fc3f032468",
      "78d953b296fb2154aa2c85e6e724ce56",
      "499ba008d5bde104ea9a1f039b3796b2",
      "ac1680d36a079a44bb58946b9d98f3fa",
	  
      "49d44c166d9f1294d8dbd78ef93df865",
      "3b69541e21f2d2c4fbf5956d0bb52768",
      "b79cf60fbaa644042b98efed62fdd4f9",
      "dd2070ece4664eb42854a564ed4dddce",
      "3c2ef5a7ef926044aa168b494f7b341f",
      "8444394f44f56b842bc2252782fde2e0",	  
	  
      "17903369fcc1aa241a87ec264597aed5",
	  
      
      "d2f7656742d00b3438d1a6ebe41e135d",	  
      "14230cf35ac2b5b45a93b13cfe478585",
      "84a9092b8430a1344a3c8b002cc68e7f",
	  
      "bd98572b88bdea94d9eb23ccf06ecfd8",
      "0d51cf14921631c40b17b6e6a3b6b1ab",
      "7fe18aed4a7a8f44289d1b262f432c16",
      "1c46157abba66934aace22a9a909dd13",
      "888fca5c7c218874c99bf78ed4b938e8",
      "088854aeb48cc7d43a6478eeed44a895"	  
	  
      "f9f179c3015a6564faef97adf87c4662",
      "21bd5d475d1526f41bc1d269e8932612",
      "094c3a16cd6e1124ca873bb96fc336c5",      
      "210218888fd34884583576d5035f46ea",	  
      "8f899ac4f1a140347a9d8049c9049125",
      "4c81642195d090448b92dc4673d7bce7",
    ],
    "icon": "17903369fcc1aa241a87ec264597aed5"
  },
  {
    "Title": "Alchemist Cognatogens",
    "Description": "",
    "Guids": [ 
      "d2f7656742d00b3438d1a6ebe41e135d",	  
      "14230cf35ac2b5b45a93b13cfe478585",
      "84a9092b8430a1344a3c8b002cc68e7f",
	  
      "bd98572b88bdea94d9eb23ccf06ecfd8",
      "0d51cf14921631c40b17b6e6a3b6b1ab",
      "7fe18aed4a7a8f44289d1b262f432c16",
      "1c46157abba66934aace22a9a909dd13",
      "888fca5c7c218874c99bf78ed4b938e8",
      "088854aeb48cc7d43a6478eeed44a895"	  
	  
      "f9f179c3015a6564faef97adf87c4662",
      "21bd5d475d1526f41bc1d269e8932612",
      "094c3a16cd6e1124ca873bb96fc336c5",      
      "210218888fd34884583576d5035f46ea",	  
      "8f899ac4f1a140347a9d8049c9049125",
      "4c81642195d090448b92dc4673d7bce7",
    ],
    "icon": "17903369fcc1aa241a87ec264597aed5"
  },
