### ISSUE TITLE
Major Bug Report: Performance hits and log bloating

### ISSUE THREAD

**Issue by TKDancer** [Truinto/SpellPouch#2]
gonna be honest and say idk what is wrong exactly  just that with the mod installed i take a huge hit to performance and it fills the player.log file with so many errors it bloats to upwards of over 4gigs over a short session, even the player.log i tried to get for testing went to over 111MB(so i cant share :/) and hundreds of thousands of lines from a single click of the bubble buff button so i can assume its having some issues using spells

![image](https://user-images.githubusercontent.com/35548194/174020498-9d8e6ae5-b96f-4c39-bd47-44f7463908f5.png)

edit: someone else in the wrath discord mod user channel mentioned also having a huge log file(over 8 gigs) and confirmed they were also using Spell Pouch

**Comment by Truinto** [comment]
Something about the resource count. So every time the game checks any of the number indicator it causes an exception. That can trigger a couple thousand times per second.
What I don't get it why it would cause an exception in the first place. I know I get these when unloading a save. Which makes sense, when you unload the game, some instances are bound to be disposed. But that's like 20 lines tops.

Never had these while playing... I can remove the log output, which solves the spam. But it leaves open why the resource count couldn't be calculated.

**Comment by Truinto** [comment]
Btw, if it's literally the same exception over and over, you don't really need to send me that file. I just need each unique exception to know what to fix.

**Comment by Truinto** [comment]
Maybe it's specific spells which cause this issue. Can you pin point which spells could be at fault? Maybe clear all group, then recreate them one by one while watching the manger log.

**Comment by Truinto** [comment]
Oh... I didn't know that HarmonyFinalizers are called even if no exception was triggered. Which meant I cause an exception every time that method returns... What a dumb bug.

**Comment by Truinto** [comment]
Should work now. Sorry for that. I don't know how that got past my testing.
