### ISSUE TITLE
1.4 GUID Issue

### ISSUE THREAD

**Issue by HohenHeizen** [Truinto/SpellPouch#3]
Although the mod seems to work on the surface it fails to register any of the GUIDs after you close a save leaving  you with a bunch of empty pouches. Beyond that functionally it seems to work.

**Comment by Truinto** [comment]
I know the update broke stuff. Please be patient until I fixed it.

**Comment by HohenHeizen** [comment]
No worries, was more of just giving a play test and stating the issue. Didn't mean to rush.
