### ISSUE TITLE
Not working correctly with 1.4x

### ISSUE THREAD

**Issue by pmabraham** [Truinto/SpellPouch#4]
Every restart of the game (i.e. save, quit for the day or for a while, start the game and continue (load last save, etc) all of the groups are lost and you have to redo everything which only remains for the current playthrough.  Can this be fixed?  Thank you!

**Comment by HohenHeizen** [comment]
If you check the DefGroups.json you should find that for whatever reason it's just not saving any of the GUIDs of the spells/abilities. Something 1.4 did behind the scenes. Hopefully whatever it is is a simple fix because I miss this mod dearly.

**Comment by Truinto** [comment]
I am working on it. It's a weird bug. But I think I have a lead.

**Comment by Truinto** [comment]
Still not working. This is getting annoying. I made sure the converter is there. Serialization is working. Deserialization is not. I made sure the type is known. Still not.

**Comment by Truinto** [comment]
I think it works now. Couldn't test it. My saves won't load because of a different mod. Feedback please.

**Comment by HohenHeizen** [comment]
> I think it works now. Couldn't test it. My saves won't load because of a different mod. Feedback please.

Could also be a corrupt GUID in your save. I've had to manually fix a few, even without mod changes.

**Comment by pmabraham** [comment]
Sadly, not fixed.  The moment you restart the game it looses the settings and the groups need to be recreated.

**Comment by ForbAvalon** [comment]
Guid still lose when restarted

**Comment by HohenHeizen** [comment]
Same experience. User created groups don't stick, but the default ones seem to, so it's a start.

**Comment by Truinto** [comment]
Ups, I forget to remove some debug code which will result in that.

**Comment by Truinto** [comment]
Updated. I realize just now I didn't test all the features. If I missed an issue, please let me know.

**Comment by pmabraham** [comment]
Fixed and thank you so much.  This mod really helps keep things simple on the action bar and related areas.
