### ISSUE TITLE
Looking through Discord comments, it looks like someone has commented that Spellpouch is not working with the updated versions of the game and/or there are issues with empty pouches - is this something others have reported?

### ISSUE THREAD

**Issue by ALFAIthildur** [Truinto/SpellPouch#7]
Looking through Discord comments, it looks like someone has commented that Spellpouch is not working with the updated versions of the game and/or there are issues with empty pouches - is this something others have reported?

"Currently no (Spellpouch does not work with 1.4). On the surface it works but it doesn't save the settings, leaving you with a bunch of empty pouches. It's currently  my biggest holdout. Should be a feature. Too many skills"

_Originally posted by @ALFAIthildur in https://github.com/Truinto/SpellPouch/discussions/6#discussioncomment-3638135_

**Comment by Truinto** [comment]
Yes it was reported and fixed a couple days ago. I am used to false alarms, but a bug report based on an old rumor is a bit much.
